import { Antonio} from "next/font/google";
import "./globals.css";

// const tourney = Tourney({
//   subsets: ["latin"],
// });

const  antonio = Antonio({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${antonio.className}`}>
        {children}
      </body>
    </html>
  );
}
